name: Featherweight Solidity CI/CD pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Prepare environment
        run: |
          sudo apt install gcc build-essential curl bubblewrap unzip ; \
          yes /usr/local/bin | bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)" ; \
          opam init ; \
          opam switch create 4.14.0 ; \
          eval $(opam env)
    
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install depedencies via OPAM
        run: |
           opam install ./ --deps-only --with-test --yes ; \
           opam install menhir qcheck-alcotest ppx_deriving_qcheck qcheck ppxlib --yes ; \
           eval $(opam env)
      
      - name: Test FS using property based testing
        working-directory: ${{ env.working-directory }}
        run: |
          eval $(opam env) ; \
          dune runtest
