name: Featherweight Solidity CI/CD pipeline
on: [push]
jobs:
  run-property-based-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14"

    runs-on: ${{ matrix.os }}
    steps:
   
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install depedencies via OPAM
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: |
           opam install ./ --deps-only --with-test --yes ; \
           opam install menhir qcheck-alcotest ppx_deriving_qcheck qcheck ppxlib --yes ; \
           eval $(opam env)
      
      - name: Test FS using property based testing
        working-directory: ${{ env.working-directory }}
        run: |
          eval $(opam env) ; \
          dune runtest
